steps:
  - name: maven:3.6.0-jdk-12-slim
    entrypoint: 'mvn'
    args: ['package']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vehicle", "."]
images: ["gcr.io/$PROJECT_ID/vehicle"]