steps:
  - name: maven:3.6.3-openjdk-14-slim
    entrypoint: 'mvn'
    args: ['package']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcp-vehicle", "."]
images: ["gcr.io/$PROJECT_ID/gcp-vehicle"]
